MVC1/MVC/Models/Course_Registration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class Course_Registration
    {
        [Key]
        [Required]
        public int R_ID { get; set; }

        public string Course_id { get; set; }

        public string Student_id { get; set; }
       

    }// class end
} // namespace end

MVC1/MVC/Controllers/DashBoardController.cs
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class DashBoardController : Controller
    {
        private UserDBContext db = new UserDBContext();
        // GET: DashBoard
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Show_Course()
        {
            return View();
        }// function end

        public ActionResult Ask_Question ()
        {
            // return View();
            string ss = Session["Email"].ToString();
            var query = (from obj in db.course_registration where (obj.Student_id ==  ss ) select obj);

            var query2 = (from b in db.list_of_course
                          join a in query
                          on b.Course_ID equals a.Course_id
                          select b);
            return View(query2);
        } // func end


        public ActionResult Course_Registration()
        {
                      /*  return View(from dd in db.course_registration
                                    join a in db.list_of_course
                                    on dd.Student_id equals Session["Email"] select a);
              */
           return View(db.list_of_course.ToList());
        } // function end

        public int Db_Insert_Course (string Student_id, string Course_id)
        {
            try
            {
                var query = from a in db.course_registration where (a.Course_id == Course_id) && (a.Student_id == Student_id) select a;
                string str = null;
                foreach (var s in query)
                {
                    str = s.Course_id;
                    break;
                } // foreach end

                if (str == null)
                {
                    Course_Registration obj = new Models.Course_Registration();
                    obj.Student_id = Student_id;
                    obj.Course_id = Course_id;

                    db.course_registration.Add(obj);
                    db.SaveChanges();
                    return 1;
                } //if end
                else
                {
                    return 2;
                }// else end

            } // try end
            catch (Exception ee)
            {
                Console.WriteLine(ee);
                return 3;
            }
        } // function end
        public ActionResult Profilee ()
        {
            int s = int.Parse(Session["id"].ToString());
            return View(db.list_of_user.Find(s));

        }// funtion end

    } // class end 
} // namespace end

MVC1/MVC/Controllers/QuestionViewModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class QuestionViewModelsController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: QuestionViewModels
        public ActionResult Index(String id)
        {
            Session["Course_Id"] = id;
            //return View(db.list_of_question.ToList());
            return View(from a in db.list_of_question
                        where a.Course_id == id
                        select a);
            
        }

        // GET: QuestionViewModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            if (questionViewModel == null)
            {
                return HttpNotFound();
            }
            return View(questionViewModel);
        }

        // GET: QuestionViewModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuestionViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Question,Question_Tag,Course_id,Sender_Email,Anonimity,IssueDate")] QuestionViewModel questionViewModel)
        {
            if (ModelState.IsValid)
            {
                db.list_of_question.Add(questionViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(questionViewModel);
        }

        // GET: QuestionViewModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            if (questionViewModel == null)
            {
                return HttpNotFound();
            }
            return View(questionViewModel);
        }

        // POST: QuestionViewModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Question,Question_Tag,Course_id,Sender_Email,Anonimity,IssueDate")] QuestionViewModel questionViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(questionViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(questionViewModel);
        }

        // GET: QuestionViewModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            if (questionViewModel == null)
            {
                return HttpNotFound();
            }
            return View(questionViewModel);
        }

        // POST: QuestionViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            db.list_of_question.Remove(questionViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC1/MVC/Views/DashBoard/Ask_Question.cshtml
@model IEnumerable<MVC.Models.ClassViewModel>
@{
    ViewBag.Title = "Ask_Question";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}


<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Course_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Instructor_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class_Description)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <th>
                @Html.DisplayFor(model => item.Course_ID)
            </th>
            <th>
                @Html.DisplayFor(model => item.Course_Name)
            </th>
            <th>
                @Html.DisplayFor(model => item.Instructor_Name)
            </th>
            <th>
                @Html.DisplayFor(model => item.Class_Description)
            </th>
          
            <td>
                @{
                    @Html.ActionLink("Answer", "Index", "QuestionViewModels", new { @id = item.Course_ID }, null)
                }

                
            </td>
        </tr>
    }

</table>

MVC1/MVC/Views/DashBoard/Course_Registration.cshtml
@model IEnumerable<MVC.Models.ClassViewModel>
@{
    ViewBag.Title = "Course_Registration";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Test.js"></script>
    <script src="~/Scripts/ie-emulation-modes-warning.js"></script>
    <script src="~/Scripts/ie10-viewport-bug-workaround.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/signin.css" rel="stylesheet" />
</head>

<h2>Course_Registration</h2>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Course_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Instructor_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class_Description)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <th>
                @Html.DisplayFor(model => item.Course_ID)
            </th>
            <th>
                @Html.DisplayFor(model => item.Course_Name)
            </th>
            <th>
                @Html.DisplayFor(model => item.Instructor_Name)
            </th>
            <th>
                @Html.DisplayFor(model => item.Class_Description)
            </th>
        </tr>
    }
</table>
<br/><br /><br /><br /><br /><br /><br />
<div class="container">

    <div class="form-signin">
        <h4 class="form-signin-heading">Course Registration</h4>

        <input id="Student_Id" placeholder="Student ID" class="form-control" value="@Session["Email"]" required autofocus type="email" />
        <input id="Course_Id" class="form-control" placeholder="Course Id" type="text" required />

        <input id="Button" class="btn btn-lg btn-primary btn-block" Text="Sign in" type="button" value="Register" />

    </div>

</div>

MVC1/MVC/Views/DashBoard/Course_Registration1.cshtml
@model IEnumerable<MVC.Models.ClassViewModel>
@{
    ViewBag.Title = "Course_Registration1";
    Layout = "~/Views/Shared/_Dashboard_layout.cshtml";
}

<h2>Course_Registration1</h2>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/Test.js"></script>
    <script src="~/Scripts/ie-emulation-modes-warning.js"></script>
    <script src="~/Scripts/ie10-viewport-bug-workaround.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/signin.css" rel="stylesheet" />
</head>

<h2>Course_Registration</h2>
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.Course_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Instructor_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class_Description)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <th>
                @Html.DisplayFor(model => item.Course_ID)
            </th>
            <th>
                @Html.DisplayFor(model => item.Course_Name)
            </th>
            <th>
                @Html.DisplayFor(model => item.Instructor_Name)
            </th>
            <th>
                @Html.DisplayFor(model => item.Class_Description)
            </th>

            <td>
                @{
                    ViewData["ID"] = item.Course_ID;
                    @Html.ActionLink("Answer", "Index", "QuestionViewModels", new { @id = item.Course_ID }, null)
                }


            </td>
        </tr>
                    }
</table>
<div class="container">

    <div class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>


        <input id="email" placeholder="Email address" class="form-control" required autofocus type="email" />
        <input id="pass" class="form-control" placeholder="Password" type="password" required />


        <input type="checkbox" value="1" class="chk" name="choice"> Student
        <input type="checkbox" value="2" class="chk" name="choice"> Teacher

        <input id="Button1" class="btn btn-lg btn-primary btn-block" Text="Sign in" type="button" value="Sign In" />

    </div>

</div>

MVC1/MVC/Views/DashBoard/Index.cshtml
@{
    Layout = null;
    //var CustomerInfo = (MVC.Models.Users)Session["Name"];

}

<!DOCTYPE html>

<html>
<head>
    <script src="~/Scripts/ie10-viewport-bug-workaround.js"></script>
    <script src="~/Scripts/ie-emulation-modes-warning.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/dashboard.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index">Piazza</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="~/DashBoard/Index">Dashboard</a></li>
                    <li><a href="#">Settings</a></li>
                    <li><a href="/DashBoard/Profilee">Profile</a></li>
                    <li><a href="#">Help</a></li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Search...">
                </form>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                    <li><a href="/DashBoard/Ask_Question">Ask Questions</a></li>
                    <li><a href="/DashBoard/Course_Registration">Course registration</a></li>
                </ul>
                
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <h1 class="page-header">Hello @Session["Name"]</h1>
               
            </div>
        </div>
    </div>
</body>
</html>

MVC1/MVC/Views/DashBoard/Profilee.cshtml
@model MVC.Models.Users

@{
    ViewBag.Title = "Profilee";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}

<h2>Profile</h2>

<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CNIC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CNIC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>