MVC1/MVC/Controllers/AnswerViewModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class AnswerViewModelsController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: AnswerViewModels
        public ActionResult Index(string id)
        {
            return View(from a in db.AnswerViewModels
                        where a.Question_id == id
                        select a);
        }

        // GET: AnswerViewModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnswerViewModel answerViewModel = db.AnswerViewModels.Find(id);
            if (answerViewModel == null)
            {
                return HttpNotFound();
            }
            return View(answerViewModel);
        }

        // GET: AnswerViewModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AnswerViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Answer,Answer_Tag,Question_id,Sender_Email,Anonimity,IssueDate")] AnswerViewModel answerViewModel)
        {
            if (ModelState.IsValid)
            {
                db.AnswerViewModels.Add(answerViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(answerViewModel);
        }

        // GET: AnswerViewModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnswerViewModel answerViewModel = db.AnswerViewModels.Find(id);
            if (answerViewModel == null)
            {
                return HttpNotFound();
            }
            return View(answerViewModel);
        }

        // POST: AnswerViewModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Answer,Answer_Tag,Question_id,Sender_Email,Anonimity,IssueDate")] AnswerViewModel answerViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answerViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(answerViewModel);
        }

        // GET: AnswerViewModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnswerViewModel answerViewModel = db.AnswerViewModels.Find(id);
            if (answerViewModel == null)
            {
                return HttpNotFound();
            }
            return View(answerViewModel);
        }

        // POST: AnswerViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AnswerViewModel answerViewModel = db.AnswerViewModels.Find(id);
            db.AnswerViewModels.Remove(answerViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC1/MVC/Controllers/QuestionViewModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class QuestionViewModelsController : Controller
    {
        private UserDBContext db = new UserDBContext();

        // GET: QuestionViewModels
        public ActionResult Index(String id)
        {
            Session["Course_Id"] = id;
            //return View(db.list_of_question.ToList());
            return View(from a in db.list_of_question
                        where a.Course_id == id
                        select a);
            
        }

        // GET: QuestionViewModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            if (questionViewModel == null)
            {
                return HttpNotFound();
            }
            return View(questionViewModel);
        }

        // GET: QuestionViewModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuestionViewModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Question,Question_Tag,Course_id,Sender_Email,Anonimity,IssueDate")] QuestionViewModel questionViewModel)
        {
            if (ModelState.IsValid)
            {
                db.list_of_question.Add(questionViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(questionViewModel);
        }

        // GET: QuestionViewModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            if (questionViewModel == null)
            {
                return HttpNotFound();
            }
            return View(questionViewModel);
        }

        // POST: QuestionViewModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Question,Question_Tag,Course_id,Sender_Email,Anonimity,IssueDate")] QuestionViewModel questionViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(questionViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(questionViewModel);
        }

        // GET: QuestionViewModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            if (questionViewModel == null)
            {
                return HttpNotFound();
            }
            return View(questionViewModel);
        }

        // POST: QuestionViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            QuestionViewModel questionViewModel = db.list_of_question.Find(id);
            db.list_of_question.Remove(questionViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC1/MVC/Views/QuestionViewModels/Create.cshtml
@model MVC.Models.QuestionViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>QuestionViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Question_Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question_Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question_Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_id, "", new { @class = "text-danger" })
            </div>
        </div>


        

        <div class="form-group">
            @Html.LabelFor(model => model.Sender_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sender_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sender_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anonimity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anonimity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anonimity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC1/MVC/Views/QuestionViewModels/Delete.cshtml
@model MVC.Models.QuestionViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>QuestionViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question_Tag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question_Tag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sender_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sender_Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anonimity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anonimity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssueDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC1/MVC/Views/QuestionViewModels/Details.cshtml
@model MVC.Models.QuestionViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}

<h2>Details</h2>

<div>
    <h4>QuestionViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question_Tag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question_Tag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sender_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sender_Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anonimity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anonimity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssueDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC1/MVC/Views/QuestionViewModels/Edit.cshtml
@model MVC.Models.QuestionViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>QuestionViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Question_Tag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Question_Tag, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Question_Tag, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Course_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Course_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Course_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sender_Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sender_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sender_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anonimity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anonimity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anonimity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC1/MVC/Views/QuestionViewModels/Index.cshtml
@model IEnumerable<MVC.Models.QuestionViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Dashboard_layout2.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Question_Tag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sender_Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssueDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Question_Tag)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course_id)
        </td>
        <td>
            @{
                if (item.Anonimity == "Y")
                {

                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Sender_Email)
                }
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IssueDate)
        </td>
        <td>
            @{
                if (item.Sender_Email == Session["Email"].ToString())
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) 

                }
            }
            |
           @{
               if (item.Sender_Email == Session["Email"].ToString())
               {
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })

                   } 
           }
           | @Html.ActionLink("Details", "Details", new
           {
               id = item.ID }) |
                 @Html.ActionLink("Answer", "Index", "AnswerViewModels", new { @id = item.ID }, null)
        </td>
    </tr>
}

</table>